import { requireAdmin } from '@/lib/auth-guard';
import { prisma } from '@/db/prisma';

interface AdminLeaseDetailPageProps {
  params: Promise<{ id: string }>;
}

export default async function AdminLeaseDetailPage({ params }: AdminLeaseDetailPageProps) {
  await requireAdmin();
  const { id } = await params;

  const lease = await prisma.lease.findUnique({
    where: { id },
    include: {
      tenant: {
        select: { name: true, email: true },
      },
      unit: {
        select: {
          name: true,
          type: true,
          property: { select: { name: true } },
        },
      },
    },
  });

  if (!lease) {
    return (
      <main className='w-full min-h-[calc(100vh-4rem)] flex items-center justify-center'>
        <p className='text-slate-500'>Lease not found.</p>
      </main>
    );
  }

  return (
    <main className='w-full px-4 py-8 md:px-0'>
      <div className='max-w-3xl mx-auto space-y-6'>
        <div>
          <h1 className='text-2xl md:text-3xl font-semibold text-slate-900 mb-1'>Lease document</h1>
          <p className='text-sm text-slate-600'>Printable lease-style summary for internal records.</p>
        </div>

        <section className='rounded-xl border border-slate-200 bg-white shadow-sm p-6 space-y-4 text-sm text-slate-700'>
          <header className='space-y-1 border-b border-slate-200 pb-4'>
            <p className='text-xs font-semibold text-slate-500 uppercase tracking-wide'>Property</p>
            <p className='text-sm text-slate-800'>
              {lease.unit.property?.name || 'Property'} • {lease.unit.name}
            </p>
            <p className='text-xs text-slate-500'>{lease.unit.type}</p>
          </header>

          <div className='grid grid-cols-1 sm:grid-cols-2 gap-4'>
            <div>
              <p className='text-xs font-semibold text-slate-500 uppercase tracking-wide'>Tenant</p>
              <p>{lease.tenant?.name || 'Tenant'}</p>
              {lease.tenant?.email && <p className='text-xs text-slate-500'>{lease.tenant.email}</p>}
            </div>
            <div>
              <p className='text-xs font-semibold text-slate-500 uppercase tracking-wide'>Lease dates</p>
              <p>
                {new Date(lease.startDate).toLocaleDateString()} –{' '}
                {lease.endDate ? new Date(lease.endDate).toLocaleDateString() : 'Ongoing'}
              </p>
            </div>
            <div>
              <p className='text-xs font-semibold text-slate-500 uppercase tracking-wide'>Monthly rent</p>
              <p>${Number(lease.rentAmount).toLocaleString()}</p>
            </div>
            <div>
              <p className='text-xs font-semibold text-slate-500 uppercase tracking-wide'>Billing day</p>
              <p>Day {lease.billingDayOfMonth} of each month</p>
            </div>
          </div>

          <div className='pt-4 border-t border-slate-200 text-xs text-slate-500 leading-relaxed space-y-2'>
            <p>
              This is a template lease summary generated by the system. It is not a legally binding document by itself.
              Use this printout together with your signed lease and any state-specific addenda.
            </p>
            <p>
              Landlord and tenant agree to the terms of the full lease agreement, including rent amount, due dates,
              late fees, house rules, and all attached addenda. This summary reflects the key economic terms only.
            </p>
          </div>
        </section>
      </div>
    </main>
  );
}
